service: newcheckstrwerere
frameworkVersion: '3.30.1'

provider:
  name: aws
  runtime: java8

# package:
#   artifact: <+artifact.path>  

functions:
  currentTime15:
    # handler: com.serverless.Handler
    image: <+artifact.image>
    events:
      - httpApi:
          path: /time
          method: get
  currentTime16:
    # handler: com.serverless.Handler
    image: <+artifact.image>
    events:
      - httpApi:
          path: /time1
          method: get         
