service: newcheckstry
frameworkVersion: '3.30.1'

provider:
  name: aws
  runtime: java8
  stackName: custom-stack-name

# package:
#   artifact: <+artifact.path>  

functions:
  currentTime51:
    # handler: com.serverless.Handler
    image: <+artifact.image>
    events:
      - httpApi:
          path: /time
          method: get
  currentTime52:
    # handler: com.serverless.Handler
    image: <+artifact.image>
    events:
      - httpApi:
          path: /time1
          method: get         
