service:
  name: remoteK8s
  identifier: remoteK8s
  orgIdentifier: default
  projectIdentifier: CDProjects
  serviceDefinition:
    spec:
      release:
        name: release-<+INFRA_KEY_SHORT_ID>
      artifacts:
        primary:
          primaryArtifactRef: <+input>
          sources:
            - spec:
                connectorRef: <+input>
                imagePath: <+input>
                tag: <+input>
                digest: ""
              identifier: fsad
              type: DockerRegistry
        sidecars:
          - sidecar:
              spec:
                connectorRef: cdplayaws
                imagePath: helm-test-chart
                tag: 0.1.0
                digest: ""
                region: us-east-1
              identifier: fsda
              type: Ecr
    type: Kubernetes
