pipeline:
    name: safddsf1234
    identifier: safddsf1234
    allowStageExecutions: false
    projectIdentifier: sdf
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: dsafadsfdf12w
              identifier: dsafadsfdf12w
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: <+input>
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              variables: []
                  infrastructure:
                      environmentRef: <+input>
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: <+input>
                              namespace: <+input>
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                name: Rollout Deployment
                                identifier: rolloutDeployment
                                type: K8sRollingDeploy
                                timeout: 10m
                                spec:
                                    skipDryRun: false
                      rollbackSteps:
                          - step:
                                name: Rollback Rollout Deployment
                                identifier: rollbackRolloutDeployment
                                type: K8sRollingRollback
                                timeout: 10m
                                spec: {}
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
        - stage:
              name: fsda
              identifier: fsda
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      useFromStage:
                          stage: dsafadsfdf12w
                  infrastructure:
                      environmentRef: sdfsdaf
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: <+input>
                              namespace: fsd
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - stepGroup:
                                name: Canary Deployment
                                identifier: canaryDepoyment
                                steps:
                                    - step:
                                          name: Canary Deployment
                                          identifier: canaryDeployment
                                          type: K8sCanaryDeploy
                                          timeout: 10m
                                          spec:
                                              instanceSelection:
                                                  type: Count
                                                  spec:
                                                      count: 1
                                              skipDryRun: false
                                    - step:
                                          type: Verify
                                          name: Verify
                                          identifier: Verify
                                          timeout: 2h
                                          spec:
                                              type: Canary
                                              spec:
                                                  sensitivity: HIGH
                                                  duration: 10m
                                                  deploymentTag: <+serviceConfig.artifacts.primary.tag>
                                          failureStrategies:
                                              - onFailure:
                                                    errors:
                                                        - Verification
                                                    action:
                                                        type: ManualIntervention
                                                        spec:
                                                            timeout: 2h
                                                            onTimeout:
                                                                action:
                                                                    type: StageRollback
                                              - onFailure:
                                                    errors:
                                                        - Unknown
                                                    action:
                                                        type: ManualIntervention
                                                        spec:
                                                            timeout: 2h
                                                            onTimeout:
                                                                action:
                                                                    type: Ignore
                                    - step:
                                          name: Canary Delete
                                          identifier: canaryDelete
                                          type: K8sCanaryDelete
                                          timeout: 10m
                                          spec: {}
                                rollbackSteps:
                                    - step:
                                          name: Canary Delete
                                          identifier: rollbackCanaryDelete
                                          type: K8sCanaryDelete
                                          timeout: 10m
                                          spec: {}
                          - stepGroup:
                                name: Primary Deployment
                                identifier: primaryDepoyment
                                steps:
                                    - step:
                                          name: Rolling Deployment
                                          identifier: rollingDeployment
                                          type: K8sRollingDeploy
                                          timeout: 10m
                                          spec:
                                              skipDryRun: false
                                rollbackSteps:
                                    - step:
                                          name: Rolling Rollback
                                          identifier: rollingRollback
                                          type: K8sRollingRollback
                                          timeout: 10m
                                          spec: {}
                      rollbackSteps: []
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
