service: my-project-134fadsaez
frameworkVersion: '2.35.0'

provider:
  name: aws
  runtime: java8

package:
  artifact: <+artifact.path>

functions:
  currentTime:
    handler: com.serverless.Handler
    events:
      - schedule: ${file(./myCustom.yml):globalSchedule}  
      - httpApi:
          path: /time
          method: get
